### ISSUE TITLE
Setup CodeShip & CodeCov for this repo

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/taggable-ui#5]
Please login to CodeShip as `numo-labs-ci` and setup the build.

**Comment by nikhilaravi** [comment]
@nelsonic I set up Codeship last week but i can't seem to access the repo on the Codeship website...
![screen shot 2016-03-29 at 09 20 34](https://cloud.githubusercontent.com/assets/5912647/14101934/9a196f52-f58f-11e5-8606-b69c26d17ebf.png)

**Comment by nelsonic** [comment]
Just tried accessing it from the `numo-labs-ci` account and get the same error:
![taggable-ui-codeship-unable-to-configure](https://cloud.githubusercontent.com/assets/194400/14102072/7049489a-f590-11e5-83a0-52b3bcdfa93f.png)

Maybe we need to contact `helpdesk@codeship.com` to get access...?

**Comment by nelsonic** [comment]
@nikhilaravi were you logged in on your own account?
The taggable-ui repo does not show up when I search for it (*logged in as `numo-labs-ui`*)
![numo-labs-codeship-search-for-tagg](https://cloud.githubusercontent.com/assets/194400/14102140/b295cba6-f590-11e5-86ae-269584a4d0df.png)

**Comment by nikhilaravi** [comment]
@nelsonic I don't think so ... I just logged into my codeship account and saw this. 
![screen shot 2016-03-29 at 12 03 00](https://cloud.githubusercontent.com/assets/5912647/14105903/3e30388a-f5a6-11e5-82de-43575d93f64b.png)

**Comment by nelsonic** [comment]
hmmm... how do you see that list?

**Comment by jackcarlisle** [comment]
@nelsonic when you click on the button to create a new project it brings you to that list

**Comment by nelsonic** [comment]
@plaenen can you please check if you are able to access the `taggable-ui` project on CodeShip?
We think it is: https://codeship.com/projects/143221/project_setup_steps/setup_scm?provider=github
but none of us are able to access it (*even logged in as `numo-labs-ci`*) ...

**Comment by nelsonic** [comment]
we are able to access the project *directly* via the URL: https://codeship.com/projects/142303
but codeship is *ignoring* pushes to the branch:
![codeship-ignores-build-for-taggable-ui](https://cloud.githubusercontent.com/assets/194400/14314857/b85bcf24-fbf1-11e5-877a-97f9e3ea50c0.png)

But we are still unable to *Navigate* to the project in the UI:
![codeship-cannot-navigate-to-numo-taggable-ui](https://cloud.githubusercontent.com/assets/194400/14314906/06e87188-fbf2-11e5-9bf8-d8e6a689fea5.png)

Un-related but *annoying*, why does CodeShip allow "Unnamed Project" ...?
![codeship-unnamed-project](https://cloud.githubusercontent.com/assets/194400/14314926/3833ef88-fbf2-11e5-9776-8a82eda27369.png)

**Comment by mlocher** [comment]
Hey folks, 

I replied on @nelsonic's ticket on our issue tracker (so we can keep track of it), afaik all of you are on the /cc list? To update this issue as well I'll copy the answer below

> the screenshots on the GitHub issue have your personal account selected in the account selector (next to the project selector). If you click on Numo Labs in the header and select the organization labelled "numo-labs-org", the project selector will update and show all projects owned by that organization, including the _taggable-ui_ project.

> As for the builds getting ignored, this is because the organization isn't on a paid subscription yet and we don't have a free tier for organization accounts. You can transfer the project back to a different account on https://codeship.com/projects/142303/configure (as long as you are an organization owner).

> As for unnamed projects, those are projects not yet connected to a GitHub / Bitbucket repository. If you don't need them feel free to delete them via the Delete button on the General settings page.

**Comment by mlocher** [comment]
Happy to help and have a great weekend ⛵
